# Generated by Django 3.0.6 on 2021-02-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeList', '0003_auto_20210218_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
