# Generated by Django 3.0.6 on 2021-02-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeList', '0005_auto_20210218_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
