# Generated by Django 3.0.6 on 2021-02-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeList', '0006_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
    ]
